//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Apple_Bss.PackageService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PackageManagementServiceSoapBinding", Namespace="http://packagemgt.webservices.elitecore.com")]
    public partial class PackageManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getOnlinePackageListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPackageDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPackageDescriptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPackageListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPackageListByFlagOperationCompleted;
        
        private System.Threading.SendOrPostCallback createPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback updatePackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletePackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPackageRenewalRuleOperationCompleted;
        
        private System.Threading.SendOrPostCallback deletePackageRenewalRuleOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPackageListByIPAddressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PackageManagementService() {
            this.Url = global::Apple_Bss.Properties.Settings.Default.Apple_Bss_PackageService_PackageManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getOnlinePackageListCompletedEventHandler getOnlinePackageListCompleted;
        
        /// <remarks/>
        public event getPackageDetailCompletedEventHandler getPackageDetailCompleted;
        
        /// <remarks/>
        public event getPackageDescriptionCompletedEventHandler getPackageDescriptionCompleted;
        
        /// <remarks/>
        public event getPackageListCompletedEventHandler getPackageListCompleted;
        
        /// <remarks/>
        public event getPackageListByFlagCompletedEventHandler getPackageListByFlagCompleted;
        
        /// <remarks/>
        public event createPackageCompletedEventHandler createPackageCompleted;
        
        /// <remarks/>
        public event updatePackageCompletedEventHandler updatePackageCompleted;
        
        /// <remarks/>
        public event deletePackageCompletedEventHandler deletePackageCompleted;
        
        /// <remarks/>
        public event addPackageRenewalRuleCompletedEventHandler addPackageRenewalRuleCompleted;
        
        /// <remarks/>
        public event deletePackageRenewalRuleCompletedEventHandler deletePackageRenewalRuleCompleted;
        
        /// <remarks/>
        public event getPackageListByIPAddressCompletedEventHandler getPackageListByIPAddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getOnlinePackageListReturn")]
        public PackageObject[] getOnlinePackageList(AuthenticationObject in0) {
            object[] results = this.Invoke("getOnlinePackageList", new object[] {
                        in0});
            return ((PackageObject[])(results[0]));
        }
        
        /// <remarks/>
        public void getOnlinePackageListAsync(AuthenticationObject in0) {
            this.getOnlinePackageListAsync(in0, null);
        }
        
        /// <remarks/>
        public void getOnlinePackageListAsync(AuthenticationObject in0, object userState) {
            if ((this.getOnlinePackageListOperationCompleted == null)) {
                this.getOnlinePackageListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOnlinePackageListOperationCompleted);
            }
            this.InvokeAsync("getOnlinePackageList", new object[] {
                        in0}, this.getOnlinePackageListOperationCompleted, userState);
        }
        
        private void OngetOnlinePackageListOperationCompleted(object arg) {
            if ((this.getOnlinePackageListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOnlinePackageListCompleted(this, new getOnlinePackageListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPackageDetailReturn")]
        public PackageObject getPackageDetail(string in0, AuthenticationObject in1) {
            object[] results = this.Invoke("getPackageDetail", new object[] {
                        in0,
                        in1});
            return ((PackageObject)(results[0]));
        }
        
        /// <remarks/>
        public void getPackageDetailAsync(string in0, AuthenticationObject in1) {
            this.getPackageDetailAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getPackageDetailAsync(string in0, AuthenticationObject in1, object userState) {
            if ((this.getPackageDetailOperationCompleted == null)) {
                this.getPackageDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPackageDetailOperationCompleted);
            }
            this.InvokeAsync("getPackageDetail", new object[] {
                        in0,
                        in1}, this.getPackageDetailOperationCompleted, userState);
        }
        
        private void OngetPackageDetailOperationCompleted(object arg) {
            if ((this.getPackageDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPackageDetailCompleted(this, new getPackageDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPackageDescriptionReturn")]
        public string getPackageDescription(string in0, AuthenticationObject in1) {
            object[] results = this.Invoke("getPackageDescription", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPackageDescriptionAsync(string in0, AuthenticationObject in1) {
            this.getPackageDescriptionAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getPackageDescriptionAsync(string in0, AuthenticationObject in1, object userState) {
            if ((this.getPackageDescriptionOperationCompleted == null)) {
                this.getPackageDescriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPackageDescriptionOperationCompleted);
            }
            this.InvokeAsync("getPackageDescription", new object[] {
                        in0,
                        in1}, this.getPackageDescriptionOperationCompleted, userState);
        }
        
        private void OngetPackageDescriptionOperationCompleted(object arg) {
            if ((this.getPackageDescriptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPackageDescriptionCompleted(this, new getPackageDescriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPackageListReturn")]
        public PackageObject[] getPackageList(int in0) {
            object[] results = this.Invoke("getPackageList", new object[] {
                        in0});
            return ((PackageObject[])(results[0]));
        }
        
        /// <remarks/>
        public void getPackageListAsync(int in0) {
            this.getPackageListAsync(in0, null);
        }
        
        /// <remarks/>
        public void getPackageListAsync(int in0, object userState) {
            if ((this.getPackageListOperationCompleted == null)) {
                this.getPackageListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPackageListOperationCompleted);
            }
            this.InvokeAsync("getPackageList", new object[] {
                        in0}, this.getPackageListOperationCompleted, userState);
        }
        
        private void OngetPackageListOperationCompleted(object arg) {
            if ((this.getPackageListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPackageListCompleted(this, new getPackageListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPackageListByFlagReturn")]
        public PackageObject[] getPackageListByFlag(bool in0, bool in1, bool in2, bool in3, AuthenticationObject in4) {
            object[] results = this.Invoke("getPackageListByFlag", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((PackageObject[])(results[0]));
        }
        
        /// <remarks/>
        public void getPackageListByFlagAsync(bool in0, bool in1, bool in2, bool in3, AuthenticationObject in4) {
            this.getPackageListByFlagAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void getPackageListByFlagAsync(bool in0, bool in1, bool in2, bool in3, AuthenticationObject in4, object userState) {
            if ((this.getPackageListByFlagOperationCompleted == null)) {
                this.getPackageListByFlagOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPackageListByFlagOperationCompleted);
            }
            this.InvokeAsync("getPackageListByFlag", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.getPackageListByFlagOperationCompleted, userState);
        }
        
        private void OngetPackageListByFlagOperationCompleted(object arg) {
            if ((this.getPackageListByFlagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPackageListByFlagCompleted(this, new getPackageListByFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("createPackageReturn")]
        public int createPackage(PackageObject in0, AuthenticationObject in1) {
            object[] results = this.Invoke("createPackage", new object[] {
                        in0,
                        in1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void createPackageAsync(PackageObject in0, AuthenticationObject in1) {
            this.createPackageAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void createPackageAsync(PackageObject in0, AuthenticationObject in1, object userState) {
            if ((this.createPackageOperationCompleted == null)) {
                this.createPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreatePackageOperationCompleted);
            }
            this.InvokeAsync("createPackage", new object[] {
                        in0,
                        in1}, this.createPackageOperationCompleted, userState);
        }
        
        private void OncreatePackageOperationCompleted(object arg) {
            if ((this.createPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createPackageCompleted(this, new createPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("updatePackageReturn")]
        public int updatePackage(string in0, PackageObject in1, AuthenticationObject in2) {
            object[] results = this.Invoke("updatePackage", new object[] {
                        in0,
                        in1,
                        in2});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void updatePackageAsync(string in0, PackageObject in1, AuthenticationObject in2) {
            this.updatePackageAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void updatePackageAsync(string in0, PackageObject in1, AuthenticationObject in2, object userState) {
            if ((this.updatePackageOperationCompleted == null)) {
                this.updatePackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdatePackageOperationCompleted);
            }
            this.InvokeAsync("updatePackage", new object[] {
                        in0,
                        in1,
                        in2}, this.updatePackageOperationCompleted, userState);
        }
        
        private void OnupdatePackageOperationCompleted(object arg) {
            if ((this.updatePackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updatePackageCompleted(this, new updatePackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("deletePackageReturn")]
        public int deletePackage(string in0, AuthenticationObject in1) {
            object[] results = this.Invoke("deletePackage", new object[] {
                        in0,
                        in1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deletePackageAsync(string in0, AuthenticationObject in1) {
            this.deletePackageAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void deletePackageAsync(string in0, AuthenticationObject in1, object userState) {
            if ((this.deletePackageOperationCompleted == null)) {
                this.deletePackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletePackageOperationCompleted);
            }
            this.InvokeAsync("deletePackage", new object[] {
                        in0,
                        in1}, this.deletePackageOperationCompleted, userState);
        }
        
        private void OndeletePackageOperationCompleted(object arg) {
            if ((this.deletePackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletePackageCompleted(this, new deletePackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("addPackageRenewalRuleReturn")]
        public int addPackageRenewalRule(RenewalRuleObject in0, AuthenticationObject in1) {
            object[] results = this.Invoke("addPackageRenewalRule", new object[] {
                        in0,
                        in1});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void addPackageRenewalRuleAsync(RenewalRuleObject in0, AuthenticationObject in1) {
            this.addPackageRenewalRuleAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void addPackageRenewalRuleAsync(RenewalRuleObject in0, AuthenticationObject in1, object userState) {
            if ((this.addPackageRenewalRuleOperationCompleted == null)) {
                this.addPackageRenewalRuleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPackageRenewalRuleOperationCompleted);
            }
            this.InvokeAsync("addPackageRenewalRule", new object[] {
                        in0,
                        in1}, this.addPackageRenewalRuleOperationCompleted, userState);
        }
        
        private void OnaddPackageRenewalRuleOperationCompleted(object arg) {
            if ((this.addPackageRenewalRuleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPackageRenewalRuleCompleted(this, new addPackageRenewalRuleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("deletePackageRenewalRuleReturn")]
        public int deletePackageRenewalRule(string in0, string in1, AuthenticationObject in2) {
            object[] results = this.Invoke("deletePackageRenewalRule", new object[] {
                        in0,
                        in1,
                        in2});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deletePackageRenewalRuleAsync(string in0, string in1, AuthenticationObject in2) {
            this.deletePackageRenewalRuleAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void deletePackageRenewalRuleAsync(string in0, string in1, AuthenticationObject in2, object userState) {
            if ((this.deletePackageRenewalRuleOperationCompleted == null)) {
                this.deletePackageRenewalRuleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeletePackageRenewalRuleOperationCompleted);
            }
            this.InvokeAsync("deletePackageRenewalRule", new object[] {
                        in0,
                        in1,
                        in2}, this.deletePackageRenewalRuleOperationCompleted, userState);
        }
        
        private void OndeletePackageRenewalRuleOperationCompleted(object arg) {
            if ((this.deletePackageRenewalRuleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deletePackageRenewalRuleCompleted(this, new deletePackageRenewalRuleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://packagemgt.webservices.elitecore.com", ResponseNamespace="http://packagemgt.webservices.elitecore.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPackageListByIPAddressReturn")]
        public PackageObject[] getPackageListByIPAddress(string in0, AuthenticationObject in1) {
            object[] results = this.Invoke("getPackageListByIPAddress", new object[] {
                        in0,
                        in1});
            return ((PackageObject[])(results[0]));
        }
        
        /// <remarks/>
        public void getPackageListByIPAddressAsync(string in0, AuthenticationObject in1) {
            this.getPackageListByIPAddressAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getPackageListByIPAddressAsync(string in0, AuthenticationObject in1, object userState) {
            if ((this.getPackageListByIPAddressOperationCompleted == null)) {
                this.getPackageListByIPAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPackageListByIPAddressOperationCompleted);
            }
            this.InvokeAsync("getPackageListByIPAddress", new object[] {
                        in0,
                        in1}, this.getPackageListByIPAddressOperationCompleted, userState);
        }
        
        private void OngetPackageListByIPAddressOperationCompleted(object arg) {
            if ((this.getPackageListByIPAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPackageListByIPAddressCompleted(this, new getPackageListByIPAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://common.containers.corporate.webservices.elitecore.com")]
    public partial class AuthenticationObject {
        
        private string iPAddressField;
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://packagemgt.containers.corporate.webservices.elitecore.com")]
    public partial class RenewalRuleObject {
        
        private int addvaluebasedonField;
        
        private int carryforwardBalanceField;
        
        private int carryforwardDataTransferField;
        
        private int carryforwardDurationField;
        
        private int carryforwardHoursField;
        
        private string newPackagenameField;
        
        private string oldPackagenameField;
        
        private int renewalruleamtflagField;
        
        private int shifttoNewField;
        
        /// <remarks/>
        public int addvaluebasedon {
            get {
                return this.addvaluebasedonField;
            }
            set {
                this.addvaluebasedonField = value;
            }
        }
        
        /// <remarks/>
        public int carryforwardBalance {
            get {
                return this.carryforwardBalanceField;
            }
            set {
                this.carryforwardBalanceField = value;
            }
        }
        
        /// <remarks/>
        public int carryforwardDataTransfer {
            get {
                return this.carryforwardDataTransferField;
            }
            set {
                this.carryforwardDataTransferField = value;
            }
        }
        
        /// <remarks/>
        public int carryforwardDuration {
            get {
                return this.carryforwardDurationField;
            }
            set {
                this.carryforwardDurationField = value;
            }
        }
        
        /// <remarks/>
        public int carryforwardHours {
            get {
                return this.carryforwardHoursField;
            }
            set {
                this.carryforwardHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string newPackagename {
            get {
                return this.newPackagenameField;
            }
            set {
                this.newPackagenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string oldPackagename {
            get {
                return this.oldPackagenameField;
            }
            set {
                this.oldPackagenameField = value;
            }
        }
        
        /// <remarks/>
        public int renewalruleamtflag {
            get {
                return this.renewalruleamtflagField;
            }
            set {
                this.renewalruleamtflagField = value;
            }
        }
        
        /// <remarks/>
        public int shifttoNew {
            get {
                return this.shifttoNewField;
            }
            set {
                this.shifttoNewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://packagemgt.containers.corporate.webservices.elitecore.com")]
    public partial class PackageObject {
        
        private string accessTimePolicyNameField;
        
        private int allottedTimeField;
        
        private double ancillaryChargeField;
        
        private string bandwidthPolicyNameField;
        
        private int billingSchemeField;
        
        private int connectionTypeField;
        
        private string dataTransferPolicyNameField;
        
        private string descriptionField;
        
        private double globalTaxChargeField;
        
        private string netSecurityStatusField;
        
        private string onlinePurchaseField;
        
        private int packageDefinitionField;
        
        private int packageDurationField;
        
        private string packageNameField;
        
        private string packageStatusField;
        
        private double packageTaxChargeField;
        
        private string poolNameField;
        
        private double priceField;
        
        private string surfingPolicyNameField;
        
        private int billCycleAmtBasedOnField;
        
        private int billDurationField;
        
        private int billingDate_DayField;
        
        private int bodAccountableValueField;
        
        private string cycleTypeField;
        
        private string fairAccessPolicyNameField;
        
        private int idleTimeoutField;
        
        private string proportionTypeField;
        
        private int countAmtBasedOnField;
        
        private string profileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string accessTimePolicyName {
            get {
                return this.accessTimePolicyNameField;
            }
            set {
                this.accessTimePolicyNameField = value;
            }
        }
        
        /// <remarks/>
        public int allottedTime {
            get {
                return this.allottedTimeField;
            }
            set {
                this.allottedTimeField = value;
            }
        }
        
        /// <remarks/>
        public double ancillaryCharge {
            get {
                return this.ancillaryChargeField;
            }
            set {
                this.ancillaryChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bandwidthPolicyName {
            get {
                return this.bandwidthPolicyNameField;
            }
            set {
                this.bandwidthPolicyNameField = value;
            }
        }
        
        /// <remarks/>
        public int billingScheme {
            get {
                return this.billingSchemeField;
            }
            set {
                this.billingSchemeField = value;
            }
        }
        
        /// <remarks/>
        public int connectionType {
            get {
                return this.connectionTypeField;
            }
            set {
                this.connectionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dataTransferPolicyName {
            get {
                return this.dataTransferPolicyNameField;
            }
            set {
                this.dataTransferPolicyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double globalTaxCharge {
            get {
                return this.globalTaxChargeField;
            }
            set {
                this.globalTaxChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string netSecurityStatus {
            get {
                return this.netSecurityStatusField;
            }
            set {
                this.netSecurityStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string onlinePurchase {
            get {
                return this.onlinePurchaseField;
            }
            set {
                this.onlinePurchaseField = value;
            }
        }
        
        /// <remarks/>
        public int packageDefinition {
            get {
                return this.packageDefinitionField;
            }
            set {
                this.packageDefinitionField = value;
            }
        }
        
        /// <remarks/>
        public int packageDuration {
            get {
                return this.packageDurationField;
            }
            set {
                this.packageDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string packageName {
            get {
                return this.packageNameField;
            }
            set {
                this.packageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string packageStatus {
            get {
                return this.packageStatusField;
            }
            set {
                this.packageStatusField = value;
            }
        }
        
        /// <remarks/>
        public double packageTaxCharge {
            get {
                return this.packageTaxChargeField;
            }
            set {
                this.packageTaxChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string poolName {
            get {
                return this.poolNameField;
            }
            set {
                this.poolNameField = value;
            }
        }
        
        /// <remarks/>
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string surfingPolicyName {
            get {
                return this.surfingPolicyNameField;
            }
            set {
                this.surfingPolicyNameField = value;
            }
        }
        
        /// <remarks/>
        public int billCycleAmtBasedOn {
            get {
                return this.billCycleAmtBasedOnField;
            }
            set {
                this.billCycleAmtBasedOnField = value;
            }
        }
        
        /// <remarks/>
        public int billDuration {
            get {
                return this.billDurationField;
            }
            set {
                this.billDurationField = value;
            }
        }
        
        /// <remarks/>
        public int billingDate_Day {
            get {
                return this.billingDate_DayField;
            }
            set {
                this.billingDate_DayField = value;
            }
        }
        
        /// <remarks/>
        public int bodAccountableValue {
            get {
                return this.bodAccountableValueField;
            }
            set {
                this.bodAccountableValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cycleType {
            get {
                return this.cycleTypeField;
            }
            set {
                this.cycleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fairAccessPolicyName {
            get {
                return this.fairAccessPolicyNameField;
            }
            set {
                this.fairAccessPolicyNameField = value;
            }
        }
        
        /// <remarks/>
        public int idleTimeout {
            get {
                return this.idleTimeoutField;
            }
            set {
                this.idleTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string proportionType {
            get {
                return this.proportionTypeField;
            }
            set {
                this.proportionTypeField = value;
            }
        }
        
        /// <remarks/>
        public int countAmtBasedOn {
            get {
                return this.countAmtBasedOnField;
            }
            set {
                this.countAmtBasedOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string profileName {
            get {
                return this.profileNameField;
            }
            set {
                this.profileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getOnlinePackageListCompletedEventHandler(object sender, getOnlinePackageListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOnlinePackageListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOnlinePackageListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PackageObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PackageObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getPackageDetailCompletedEventHandler(object sender, getPackageDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPackageDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPackageDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PackageObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PackageObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getPackageDescriptionCompletedEventHandler(object sender, getPackageDescriptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPackageDescriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPackageDescriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getPackageListCompletedEventHandler(object sender, getPackageListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPackageListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPackageListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PackageObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PackageObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getPackageListByFlagCompletedEventHandler(object sender, getPackageListByFlagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPackageListByFlagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPackageListByFlagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PackageObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PackageObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void createPackageCompletedEventHandler(object sender, createPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void updatePackageCompletedEventHandler(object sender, updatePackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updatePackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updatePackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deletePackageCompletedEventHandler(object sender, deletePackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deletePackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deletePackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void addPackageRenewalRuleCompletedEventHandler(object sender, addPackageRenewalRuleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addPackageRenewalRuleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addPackageRenewalRuleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void deletePackageRenewalRuleCompletedEventHandler(object sender, deletePackageRenewalRuleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deletePackageRenewalRuleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deletePackageRenewalRuleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getPackageListByIPAddressCompletedEventHandler(object sender, getPackageListByIPAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPackageListByIPAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPackageListByIPAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PackageObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PackageObject[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591