//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apple_Bss.UI.SystemManagement {
    
    
    public partial class Default {
        
        /// <summary>
        /// LoggedActivity1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Apple_Bss.UserControl.LoggedActivity LoggedActivity1;
    }
}
