//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apple_Bss.UI.TechnicalSupport.HelpDesk {
    
    
    public partial class ClientSearchView {
        
        /// <summary>
        /// ClientSearchView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Apple_Bss.UserControl.ClientSearchView ClientSearchView1;
    }
}
